export function generatePrd(pack){return {title:'Saved views for operational alerts',status:'Draft',generatedAt:new Date().toISOString(),
problem:'Operations teams repeatedly rebuild the same alert filters at the start of each shift. This slows triage and makes handoffs inconsistent.',
goals:[{goal:'Reduce time to a useful alert queue',metric:'Median time from sign-in to filtered queue falls from 90 seconds to under 20 seconds.'},{goal:'Make recurring triage workflows reusable',metric:'30% of weekly active operators create or use a saved view within 30 days.'}],
nonGoals:['Team-shared views in the first release','Changing alert routing or notification rules','Replacing advanced search'],
stories:[{title:'Save the current alert view',owner:'Maya (Frontend)',effort:'M',description:'As an operator, I want to save my current filters, sort order, and scope so I can return to the same queue without rebuilding it.',criteria:['Save is available only when at least one filter or sort differs from default.','A saved view restores filters, sort order, and alert scope exactly.','Duplicate names prompt for a new name.']},{title:'Manage personal saved views',owner:'Theo (Platform)',effort:'S',description:'As an operator, I want to rename or delete my own saved views so my picker stays useful.',criteria:['Only the owner can rename or delete a view.','Deletion requires confirmation and returns to the default view.']},{title:'Empty state and limit handling',owner:'Maya (Frontend)',effort:'S',description:'As a new operator, I need to understand saved views before I have any.',criteria:['Empty state explains the value and shows how to save a view.','Limit is 25 views per user and is explained before save fails.']}],
design:'Use the existing alert-filter bar. Add a compact “Views” picker on the left, followed by “Save view”. The picker includes personal views, last-used timestamp, and management controls. Figma frames: View picker, Save current view modal, Empty state.',
questions:[{question:'Should users be able to share a saved view with a team?',owner:'Priya, Product',why:'Slack thread identified this as useful, but it adds permissions and ownership complexity.'},{question:'What is the default cap for saved views?',owner:'Theo, Platform',why:'A limit is needed to keep picker performance predictable.'}],
rollout:[{phase:'Dogfood',detail:'Internal operations team, 2 weeks. Instrument save, apply, rename, delete.'},{phase:'Beta',detail:'10 design partners. Monitor time-to-queue and support tickets.'},{phase:'General availability',detail:'Release to all operators after no P1 workflow regressions.'}],
modelContract:{model:process.env.OPENAI_MODEL||'gpt-5.6',context:['Loom transcript and visual descriptions','Slack decisions and open questions','Figma frames','past PRD template and voice'],reason:'GPT-5.6 fuses long, contradictory source context into a structured, traceable product decision artifact.'}}}
export function decompose(prd){return {epic:{title:`[Epic] ${prd.title}`,status:'Suggested'},tickets:prd.stories.map((s,i)=>({id:`ENG-${214+i}`,title:s.title,owner:s.owner,effort:s.effort,criteria:s.criteria,status:'Ready to create'}))}}
